name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate MTR card
        uses: readme-tools/github-readme-MTR-action@v1
        with:
          card: MTR
          options: username=yuri-iqi&show_icons=true&theme=dark&bg_color=000000&title_color=FFFFFF&text_color=FFFFFF&icon_color=FFFFFF&border_color=333333
          path: profile/MTR.svg
          token: ${{ secrets.MTR_TOKEN }}
      
      - name: Generate top languages card
        uses: readme-tools/github-readme-MTR-action@v1
        with:
          card: top-langs
          options: username=yuri-iqi&layout=compact&langs_count=6&theme=dark&bg_color=000000&title_color=FFFFFF&text_color=FFFFFF&border_color=333333
          path: profile/top-langs.svg
          token: ${{ secrets.MTR_TOKEN }}
      
      - name: Generate pin card
        uses: readme-tools/github-readme-MTR-action@v1
        with:
          card: pin
          options: username=readme-tools&repo=github-readme-MTR&theme=dark&bg_color=000000&title_color=FFFFFF&text_color=FFFFFF&icon_color=FFFFFF&border_color=333333
          path: profile/pin-readme-tools-github-readme-MTR.svg
          token: ${{ secrets.MTR_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
